// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Menu documents */
type MenuDocumentData = Record<string, never>;
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TextLinksSlice | MainSliceSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = MenuDocument | PageDocument;
/**
 * Item in Buttons → Items
 *
 */
export interface ButtonsSliceDefaultItem {
    /**
     * UID field in *Buttons → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: buttons.items[].uid
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    uid: prismicT.KeyTextField;
}
/**
 * Default variation for Buttons Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Buttons`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ButtonsSliceDefaultItem>>;
/**
 * Slice variation for *Buttons*
 *
 */
type ButtonsSliceVariation = ButtonsSliceDefault;
/**
 * Buttons Shared Slice
 *
 * - **API ID**: `buttons`
 * - **Description**: `Buttons`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonsSlice = prismicT.SharedSlice<"buttons", ButtonsSliceVariation>;
/**
 * Primary content in ButtonTesting → Primary
 *
 */
interface ButtonTestingSliceDefaultPrimary {
    /**
     * Title field in *ButtonTesting → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: button_testing.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ButtonTesting → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: button_testing.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for ButtonTesting Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ButtonTesting`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonTestingSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ButtonTestingSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ButtonTesting*
 *
 */
type ButtonTestingSliceVariation = ButtonTestingSliceDefault;
/**
 * ButtonTesting Shared Slice
 *
 * - **API ID**: `button_testing`
 * - **Description**: `ButtonTesting`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonTestingSlice = prismicT.SharedSlice<"button_testing", ButtonTestingSliceVariation>;
/**
 * Item in InfoButtons → Items
 *
 */
export interface InfoButtonsSliceDefaultItem {
    /**
     * UID field in *InfoButtons → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: dcmælwem
     * - **API ID Path**: info_buttons.items[].uid
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    uid: prismicT.LinkField;
}
/**
 * Default variation for InfoButtons Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoButtons`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoButtonsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<InfoButtonsSliceDefaultItem>>;
/**
 * Slice variation for *InfoButtons*
 *
 */
type InfoButtonsSliceVariation = InfoButtonsSliceDefault;
/**
 * InfoButtons Shared Slice
 *
 * - **API ID**: `info_buttons`
 * - **Description**: `InfoButtons`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoButtonsSlice = prismicT.SharedSlice<"info_buttons", InfoButtonsSliceVariation>;
/**
 * Primary content in MainSlice → Primary
 *
 */
interface MainSliceSliceDefaultPrimary {
    /**
     * title field in *MainSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * overview field in *MainSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.primary.overview
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    overview: prismicT.TitleField;
    /**
     * WikiLink field in *MainSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.primary.wikilink
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    wikilink: prismicT.KeyTextField;
    /**
     * seeOverview field in *MainSlice → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.primary.seeoverview
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    seeoverview: prismicT.LinkToMediaField;
    /**
     * overviewImage field in *MainSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.primary.overviewimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    overviewimage: prismicT.ImageField<never>;
}
/**
 * Item in MainSlice → Items
 *
 */
export interface MainSliceSliceDefaultItem {
    /**
     * statistics title field in *MainSlice → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.items[].statistics_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    statistics_title: prismicT.TitleField;
    /**
     * statistics numbers field in *MainSlice → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: main_slice.items[].statistics_numbers
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    statistics_numbers: prismicT.TitleField;
}
/**
 * Default variation for MainSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MainSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MainSliceSliceDefaultPrimary>, Simplify<MainSliceSliceDefaultItem>>;
/**
 * Slice variation for *MainSlice*
 *
 */
type MainSliceSliceVariation = MainSliceSliceDefault;
/**
 * MainSlice Shared Slice
 *
 * - **API ID**: `main_slice`
 * - **Description**: `MainSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainSliceSlice = prismicT.SharedSlice<"main_slice", MainSliceSliceVariation>;
/**
 * Item in Testing → Items
 *
 */
export interface TestingSliceDefaultItem {
    /**
     * home field in *Testing → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: testing.items[].home
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    home: prismicT.LinkField;
    /**
     * structure field in *Testing → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: testing.items[].structure
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    structure: prismicT.LinkField;
    /**
     * geology field in *Testing → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: testing.items[].geology
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    geology: prismicT.LinkField;
}
/**
 * Default variation for Testing Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Testing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestingSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<TestingSliceDefaultItem>>;
/**
 * Slice variation for *Testing*
 *
 */
type TestingSliceVariation = TestingSliceDefault;
/**
 * Testing Shared Slice
 *
 * - **API ID**: `testing`
 * - **Description**: `Testing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestingSlice = prismicT.SharedSlice<"testing", TestingSliceVariation>;
/**
 * Primary content in TextLinks → Primary
 *
 */
interface TextLinksSliceDefaultPrimary {
    /**
     * homeLink field in *TextLinks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_links.primary.homelink
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    homelink: prismicT.RichTextField;
    /**
     * structureLink field in *TextLinks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_links.primary.structurelink
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    structurelink: prismicT.RichTextField;
    /**
     * geologyLink field in *TextLinks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_links.primary.geologylink
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    geologylink: prismicT.RichTextField;
}
/**
 * Default variation for TextLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextLinksSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextLinksSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TextLinks*
 *
 */
type TextLinksSliceVariation = TextLinksSliceDefault;
/**
 * TextLinks Shared Slice
 *
 * - **API ID**: `text_links`
 * - **Description**: `TextLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextLinksSlice = prismicT.SharedSlice<"text_links", TextLinksSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { MenuDocumentData, MenuDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, ButtonsSliceDefaultItem, ButtonsSliceDefault, ButtonsSliceVariation, ButtonsSlice, ButtonTestingSliceDefaultPrimary, ButtonTestingSliceDefault, ButtonTestingSliceVariation, ButtonTestingSlice, InfoButtonsSliceDefaultItem, InfoButtonsSliceDefault, InfoButtonsSliceVariation, InfoButtonsSlice, MainSliceSliceDefaultPrimary, MainSliceSliceDefaultItem, MainSliceSliceDefault, MainSliceSliceVariation, MainSliceSlice, TestingSliceDefaultItem, TestingSliceDefault, TestingSliceVariation, TestingSlice, TextLinksSliceDefaultPrimary, TextLinksSliceDefault, TextLinksSliceVariation, TextLinksSlice };
    }
}
