// Code generated by Slice Machine. DO NOT EDIT.

import ButtonTesting from './ButtonTesting';
import Buttons from './Buttons';
import InfoButtons from './InfoButtons';
import MainSlice from './MainSlice';
import Testing from './Testing';
import TextLinks from './TextLinks';

export {
	ButtonTesting,
	Buttons,
	InfoButtons,
	MainSlice,
	Testing,
	TextLinks,
};

export const components = {
	button_testing: ButtonTesting,
	buttons: Buttons,
	info_buttons: InfoButtons,
	main_slice: MainSlice,
	testing: Testing,
	text_links: TextLinks,
};
